#!/bin/bash
# AUTHOR: Abhishek Tamrakar
# EMAIL: abhishek.tamrakar08@gmail.com
# VERSION: 1.1.0
# LICENSE: Copyright (C) 2018 Abhishek Tamrakar
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
#define variables
KUBECTL=$(which kubectl)
GET=$(which egrep)
AWK=$(which awk)
TMUX=$(which tmux)
SCRIPT=${0##*/}
NEWSESSION="${SCRIPT%%.*}$RANDOM"
# define functions
usage()
{
  cat <<_EOF_
    $SCRIPT <options>

    options:
        -n|--namespace:  kubernetes NAMESPACE or export NAMESPACE=<value>
        -s|--session:    Session Name for TMUX
        -e|--show-error: Show only errored pods
        -h|--help:       Print this help and quit
_EOF_

exit 1
}

info()
{
  printf '\n%s: %s\n' "INFO" "$@"
}

warn()
{
  printf '\n%s: %s\n' "WARN" "$@"
}

fatal()
{
  printf '\n%s: %s\n' "ERROR" "$@"
  exit 1
}

check_commands()
{
  CMDS=(TMUX KUBECTL)
  for CMD in ${CMDS[@]}
  do
     if [ x${!CMD} = x ]; then
       fatal "${CMD,,} not found"
     fi
  done
}

destroy()
{
  $TMUX kill-server 2>/dev/null \
    && info "All sessions killed"
}

start_server()
{
  $TMUX start-server \
    || fatal "Failed to start tmux server"
}

check_session()
{
  if $TMUX has-session -t $THIS_SESSION 2>/dev/null;
  then
    IS_SESSION=0
  else
    IS_SESSION=1
  fi
}

create_session()
{
  $TMUX new-session -d -s $THIS_SESSION \
    || fatal "Cannot create session"
  $TMUX set-window-option -g automatic-rename off
}

start_split()
{
  local n=$1
  check_session
  if [ $IS_SESSION -eq 1 ]; then
    # create session
    start_server
    create_session
  fi
  $TMUX selectp -t $n \; \
    splitw $COMMAND \; \
    select-layout tiled \;
}

run_kubectl_command()
{
  # only for use with plugin.
  local THIS_NAMESPACE=${1}
  local THIS_SESSION=${2}
  local SHOWERROR="${3}"
  n=0
  while IFS=' ' read -r POD CONTAINERS
  do
    $TMUX neww $COMMAND -n $POD 2>/dev/null
    for CONTAINER in ${CONTAINERS//,/ }
    do
      if [ x$POD = x -o x$CONTAINER = x ]; then
        # if any of the values is null, exit.
        warn "Looks like there is a problem getting pods data."
        break
      fi
      if [ ${SHOWERROR:-0} -eq 1 ]; then
        # if enabled
        COMMAND="$KUBECTL logs -f $POD -c $CONTAINER -n $NAMESPACE | $GET '[Ee]rror|[E]RROR|[Ww]arn|[W]ARN|[Ee]xception'"
      else
        #normal run
        COMMAND="$KUBECTL logs -f $POD -c $CONTAINER -n $NAMESPACE"
      fi

      start_split $n
    done
    $TMUX renamew $POD 2>/dev/null
    ((n+=1))
  done< <($KUBECTL get pods -n $NAMESPACE \
	--ignore-not-found=true \
	-o=custom-columns=NAME:.metadata.name,CONTAINERS:.spec.containers[*].name \
	--no-headers=true)

  attach_sessions
}

attach_sessions()
{
  $TMUX selectw -t $THIS_SESSION:1 \; \
  attach-session -t $THIS_SESSION\;
}
#
# interrupt or quit
trap destroy 2 3 15 EXIT
#
# run
while [ $# -gt 0 ]; do
  case $1 in
  -n|--namespace) shift; NAMESPACE=$1;;
  -s|--session) shift; SESSION_NAME=$1;;
  -e|--show-error) SHOWERROR=1;;
  -h|--help) usage;;
  *) fatal "invalid option $1";;
  esac
  shift;
done

# check number of arguments
if [[ "x${NAMESPACE}" = "x" ]]; then
  fatal "At least one namespace is required!"
fi

# check cli availability
check_commands

# check k8s version compatibility
COMPATIBLE_KUBECTL_VERSION=$($KUBECTL version --client --short| \
  awk -F': ' '{ \
    gsub("v","",$2); \
    split($2,a,"."); \
    if (a[1] == 1 && a[2] < 12) print "no"; else print "yes" \
  }' \
)

if [[ "$COMPATIBLE_KUBECTL_VERSION" = "no" ]]; then
  fatal "kubectl version is incompatible, please correct and try again."
fi

if [[ "x${SESSION_NAME}" = "x" ]]; then
  SESSION_NAME=$NEWSESSION
fi
# run kubectl cli to get details
run_kubectl_command ${NAMESPACE} ${SESSION_NAME} ${SHOWERROR}
